### ISSUE TITLE
add node_modules to .gitignore

### ISSUE THREAD

**Issue by hunan-rostomyan** [jeffreysbrother/css_slider#2]
The *node_modules/* directory is making the repo bigger than it needs to be (so takes some time to pull). You can add it to your *.gitignore* so that it stays out of version control. As long as you share the *package.json*, others can generate that directory themselves.

**Comment by jeffreysbrother** [comment]
That's right! I've been forgetting to do this on all my recent projects. Thanks so much, Hunan.
